### ISSUE TITLE
I'm unable to get ImageCoin.service to start on Ubuntu18.04 for Masternode. Any advice?

### ISSUE THREAD

**Issue by ajsingh007** [mceme/ImageCoin#34]
Some output from the terminal when using the shell script:

● ImageCoin.service - ImageCoin service
   Loaded: loaded (/etc/systemd/system/ImageCoin.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-04-11 00:04:15 UTC; 1min 36s ago
  Process: 3116 ExecStart=/usr/local/bin/ImageCoind -daemon -conf=/root/.imagecoincore/imagecoin.conf -datadir=/root/.imagecoincore (code=exited, status=127)

Apr 11 00:04:15 img-mn1 systemd[1]: ImageCoin.service: Control process exited, code=exited status=127
Apr 11 00:04:15 img-mn1 systemd[1]: ImageCoin.service: Failed with result 'exit-code'.
Apr 11 00:04:15 img-mn1 systemd[1]: Failed to start ImageCoin service.
Apr 11 00:04:15 img-mn1 systemd[1]: ImageCoin.service: Service hold-off time over, scheduling restart.
Apr 11 00:04:15 img-mn1 systemd[1]: ImageCoin.service: Scheduled restart job, restart counter is at 6.
Apr 11 00:04:15 img-mn1 systemd[1]: Stopped ImageCoin service.
Apr 11 00:04:15 img-mn1 systemd[1]: ImageCoin.service: Start request repeated too quickly.
Apr 11 00:04:15 img-mn1 systemd[1]: ImageCoin.service: Failed with result 'exit-code'.
Apr 11 00:04:15 img-mn1 systemd[1]: Failed to start ImageCoin service.

Thanks in advance for any insight!

**Comment by edgeball** [comment]
I've been having the same error

**Comment by mceme** [comment]
Run with root user

**Comment by ajsingh007** [comment]
hm I was running as root and entered the private key I generated in the debug console but no luck. Nbd -- I'll close this issue in the meantime and try again as time allows. Thank you!
