### ISSUE TITLE
Block decode failed

### ISSUE THREAD

**Issue by Poolmin** [mceme/ImageCoin#36]
I would add imgcoin to yiimp pool but when I try to mine block
I get error "Block decode failed"
No advice in debug.log

Can you give me some information for fixing it ?

**Comment by mceme** [comment]
you need change code , with new parameter of block "imgbase64"

https://github.com/zone117x/node-stratum-pool

**Comment by Poolmin** [comment]
Hello you mean I add to change code in coinbase.cpp right (coinbase_create
function) ?
https://github.com/tpruvot/yiimp/blob/next/stratum/coinbase.cpp

Where I have to add new imgbase64 parameter, have you some documentation
that  I can read ?

Il giorno gio 18 apr 2019 alle ore 00:00 mceme <notifications@github.com>
ha scritto:

**Comment by mceme** [comment]
No documentation , other pools solve this by own

**Comment by mceme** [comment]
News ! can use
https://github.com/mceme/yiimp

cd stratum
make

**Comment by Browster** [comment]
ok this is common problem with most wallets to solve this you need blocks and chainstate downloaded for the image coin I am not sure where to get them though

**Comment by mceme** [comment]
Here https://github.com/mceme/ImageCoin/releases/download/1.0.24.1/24_04_2019blocks.zip

**Comment by ma7555** [comment]
I am having this issue, after trying mceme fork the stratum is crashing
```./run-img.sh: line 11:  1310 Aborted                 (core dumped) ./stratum-img config/$1```
