### ISSUE TITLE
SQL ERROR: 1054, Unknown column 'fee' in 'field list'

### ISSUE THREAD

**Issue by 857487** [mceme/ImageCoin#38]
1:03:42: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:03:44: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:03:44: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:03:46: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:03:46: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:03:48: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:03:48: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:03:50: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:03:50: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:03:52: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:03:52: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:03:54: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:03:54: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:03:56: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:03:56: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:03:58: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:03:58: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:04:00: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:04:00: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:04:02: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:04:02: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:04:04: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:04:04: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:04:06: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:04:06: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:04:08: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:04:08: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:04:10: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533
21:04:10: SQL ERROR: 1054, Unknown column 'fee' in 'field list'
21:04:12: 2019-04-30 starting stratum for x11 on 192.168.88.10:3533

**Comment by mceme** [comment]
Fixed
