### ISSUE TITLE
Huge getblocktemplate result size

### ISSUE THREAD

**Issue by Poolmin** [mceme/ImageCoin#39]
Hello,
I manage to add imagecoin on pool but unfortunately after a while when pool inquiry chain with getblocktemplate command get back a huge result.

I experienced that many times and the size of response is around 90MB. This obiovously slow down pool...

Huge data are into the transaction field and data subfield in that way:
I post only the first row.

{
  "capabilities": [
    "proposal"
  ],
  "version": 536870912,
  "rules": [
  ],
  "vbavailable": {
  },
  "vbrequired": 0,
  "previousblockhash": "0000000000005224eeaadc8bdd6bc26743d9263e48afc8ebb4054e9ff2b69d35",
  "transactions": [
    {
      "data": "0100000001e06538d82accbdefa3876da6992c7753c7b459cd45d7f4ba6fce47acffbd9fe5010000006a4730440220589eb3d7eb7d03
d77431a74cb0875134cefe506ce95093d14ca8da233a4a1e1e02207aa1194b30f517ec59c37c0bf8cb2f737a9841d3e84afcfbc36081d331f826d901210
26672882166e62056b196527eca6c89a5630f438ded62fdb3c2c2546e603fd4a7feffffff02def81500000000001976a9143d0970132fff27884010acdc
2bc49fd41ea6290288ac0080c3c901000000001976a9148e2d7913703e98f35218478cdee16af440eeaa4088acfeb82b970055457344424251414141414
941487931695535694b304a795942734c414141414541414f414141416247396e4c6a41774d4441774d4441784d44524d7537764f2b3137373576556241
554a557777456738573851685973346a70303448577435762f6679337162794c743776596a76655444506c314277497856516a4e4f5749416f6b4b684d5
14a4943484e436441672f4e5837663946724b592b6a4b4537733566752b72732b6c334d392f2f482f2b35562f2f3156392f2f6657662f547668762f3833
2f38562f2b74642f2b6465663757392f2f327a45502f3331462f572f2f663474646a332f582f3746582f2b367550622f3854726d50376e322f2f76314f4
9692f2f74714a763733332f2f71762f2f6f724e536b59563439345075725772496555436873567934626333516e63504958663876497254514a7a56494f
6149444555564f2f4d654946654c5177706c5331554964305061423634706135776430384a7a554a6531314c5a43514b334e4648714d2f724246612f426
83543644d39573746534835516f4c3931685847436d68727343463041334a39393472644363586e4b6333747253684b4675425a4577364678566d424d55
6e756f4172734c48504a69426d4745315857393032546c4e79636767685432452b6f596a38744b6c4e3639526e4a2f2b5378584b5a75336678613856415
52b4b322b4a754e75547245574c6f71513950464c51344a3756656c573030305034764d7a35693648656c4152545049686658623166476355364a756c4e
5046594c7a666b6659547068384a7964356a594b477245454d393344452b52552b68734a7268514650696e6f6367794871546b423235624b7163422b756
f647a75716f64466542754b664b7476564e6f5252366a664332753563376b2f3841794e7a674843784f4c32336470446d66746370356f7a574e3578796c
36666748593157595a6d796b384a4157485845563559687449623166633167756d4b30785447527949434535496f4837563671352b576b2f3557765a474
d4e5345783541734a31656b5574623036397657576e7542685962573477457178466e426d565a437843615976776a65726e3330354c7a614f66616c7777
6a4f514c576c72496a496a51664f536e6e704d7a2b4b48454433337a786b4b797068473572413536356b796b36764c304133753034726f76687a766c5a6
13158714a6b756e6a386634636a374b367a6b375a647273346c316755794f3963595a2b4b4c6142512f4a41565656414958674b6a692f536b6950464178
7832612b6b35322b416f517949314b7156446438624458394774736e4c5544364f7979573748366e67416e7866756f5033562b45335349556d4b5563657
76247356b706374466f756447395668357a47456f786b53384f37503754756d4e6b53444e634e2f5577446e47375a766645655a544f444241444e657a6e
5157376c67594877326b3843323163342b5648597a4751564d4448563351424b6f42796c7153383065693935765a75484e2f4b46644c6653575859634d4
a6f596f5136795a6559506650484a4e3757304d3268375451502b576e6e42516c43627663486641694c5452594e6d786355546541472b4f5442364f4973
4f6a7057425344736c32496b6632704f7943756953304a3637624c434a2f357452376f556845654439643664592b45396c57476c7651764354734967304
9714b6f4e316368456f2f65726e73756b3565566d4935416f47314b4a726462753831486e427654346a42645a716679463458355a7562454563355a314f
--More--

I'm wondering if this is normal behaviour or if there's something we can do to avoid that.

**Comment by mceme** [comment]
please start daemon with cmd  

sudo ImageCoind -daemon -blockmaxsize=9000000 -blockprioritysize=4000005

**Comment by Poolmin** [comment]
Thank you I use the conf file can I add 

blockmaxsize=9000000 
blockprioritysize=4000005

In conf file ?

**Comment by mceme** [comment]
yes but try

**Comment by Poolmin** [comment]
poolmin.com now wallet is offline :-(

**Comment by mceme** [comment]
add to conf 
daemon=1
