### ISSUE TITLE
rpc error with daemon instance 0 when submitting block with submitblock {"code":-22,"message":"Block decode failed"}

### ISSUE THREAD

**Issue by jeromemorignot** [mceme/ImageCoin#57]
Hi,

When using NOMP or UNOMP, the submission of mined blocks fails : 
rpc error with daemon instance 0 when submitting block with submitblock {"code":-22,"message":"Block decode failed"}

What is the format of the block? It is apparently not the standard? Is there any whitepaper?

Thank you!

**Comment by mceme** [comment]
Yes stratum yiimp need modifition , 

Use https://github.com/mceme/yiimp-ImageCoin/blob/next/stratum/stratum

**Comment by jeromemorignot** [comment]
I didnt ask for Yiimp...I asked about the structure of the block so that I can adjust NOMP!
