### ISSUE TITLE
I'm unable to get ImageCoin.service to start on Ubuntu18.04 for Masternode

### ISSUE THREAD

**Issue by GJT67** [mceme/ImageCoin#64]
● ImageCoin.service - ImageCoin service
Loaded: loaded (/etc/systemd/system/ImageCoin.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Thu 2019-12-16 00:04:15 UTC; 1min 36s ago
Process: 3116 ExecStart=/usr/local/bin/ImageCoind -daemon -conf=/root/.imagecoincore/imagecoin.conf -datadir=/root/.imagecoincore (code=exited, status=127

**Comment by mceme** [comment]
run with root user

**Comment by GJT67** [comment]
OK
