### ISSUE TITLE
WATCHDOG_EXPIRED

### ISSUE THREAD

**Issue by GJT67** [mceme/ImageCoin#65]
Followed the guide, but the test gave me errors ?
root@imagemasternode:~/sentinel# ./venv/bin/py.test ./test
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.17, pytest-3.0.1, py-1.4.31, pluggy-0.3.1
rootdir: /root/sentinel, inifile:
collected 23 items

test/integration/test_jsonrpc.py F
test/unit/test_dash_config.py .
test/unit/test_dashd_data_shims.py ..
test/unit/test_dashy_things.py FF....
test/unit/test_misc.py .
test/unit/test_models.py ..
test/unit/test_submit_command.py .
test/unit/models/test_proposals.py F..F
test/unit/models/test_superblocks.py F..FF

======================================================= FAILURES =======================================================
______________________________________________________ test_dashd ______________________________________________________

    def test_dashd():
>       config_text = SibcoinConfig.slurp_config_file(config.sibcoin_conf)
E       AttributeError: 'module' object has no attribute 'sibcoin_conf'

test/integration/test_jsonrpc.py:16: AttributeError
_______________________________________________ test_valid_dash_address ________________________________________________

    def test_valid_dash_address():
        from dashlib import is_valid_address

        main = valid_dash_address()
        test = valid_dash_address('testnet')

>       assert is_valid_address(main) is True

test/unit/test_dashy_things.py:70:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
lib/dashlib.py:102: in is_valid_address
    return is_valid_imagecoin_address(address, network)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

address = 'Sa9Vn2V4gtBFHovqVQh5V6dCt4ukMYUU2Z', network = 'mainnet'

    def is_valid_imagecoin_address(address, network='mainnet'):
>       raise RuntimeWarning('This method should not be used with sibcoin')
E       RuntimeWarning: This method should not be used with sibcoin

lib/dashlib.py:45: RuntimeWarning
______________________________________________ test_invalid_dash_address _______________________________________________

    def test_invalid_dash_address():
        from dashlib import is_valid_address

        main = invalid_dash_address()
        test = invalid_dash_address('testnet')

>       assert is_valid_address(main) is False

test/unit/test_dashy_things.py:85:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
lib/dashlib.py:102: in is_valid_address
    return is_valid_imagecoin_address(address, network)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

address = 'Sa9Vn2V4gtBFHovqVQh5V6dCt4ukMYUU2Y', network = 'mainnet'

    def is_valid_imagecoin_address(address, network='mainnet'):
>       raise RuntimeWarning('This method should not be used with sibcoin')
E       RuntimeWarning: This method should not be used with sibcoin

lib/dashlib.py:45: RuntimeWarning
________________________________________________ test_proposal_is_valid ________________________________________________

proposal = <models.Proposal object at 0x7f8669496090>

    def test_proposal_is_valid(proposal):
        from sibcoind import SibcoinDaemon
        import dashlib
>       dashd = SibcoinDaemon.from_sibcoin_conf(config.sibcoin_conf)
E       AttributeError: 'module' object has no attribute 'sibcoin_conf'

test/unit/models/test_proposals.py:83: AttributeError
_______________________________________________ test_approved_and_ranked _______________________________________________

go_list_proposals = [{'AbsoluteYesCount': 11, 'AbstainCount': 0, 'CollateralHash': '996eae8ba8dbe5152ccb302ba513cf59b79fa95a7899fe34519804...43930333131303237222c2274797065223a312c2275726c223a2268747470733a2f2f736962636f696e2e6f72672f7465737432227d5d5d', ...}]

    def test_approved_and_ranked(go_list_proposals):
        from sibcoind import SibcoinDaemon
>       sibcoind = SibcoinDaemon.from_sibcoin_conf(config.sibcoin_conf)
E       AttributeError: 'module' object has no attribute 'sibcoin_conf'

test/unit/models/test_proposals.py:242: AttributeError
_______________________________________________ test_superblock_is_valid _______________________________________________

superblock = <models.Superblock object at 0x7f866a098310>

    def test_superblock_is_valid(superblock):
        from sibcoind import SibcoinDaemon
>       sibcoind = SibcoinDaemon.from_sibcoin_conf(config.sibcoin_conf)
E       AttributeError: 'module' object has no attribute 'sibcoin_conf'

test/unit/models/test_superblocks.py:127: AttributeError
________________________________________ test_deterministic_superblock_creation ________________________________________

go_list_proposals = [{'AbsoluteYesCount': 1000, 'AbstainCount': 7, 'CollateralHash': 'acb67ec3f3566c9b94a26b70b36c1f74a010a37c0950c22d683c...26c223a2022687474703a2f2f736962636f6e74726f6c2e6f72672f70726f706f73616c732f6665726e616e64657a2d37363235227d5d5d', ...}]

    def test_deterministic_superblock_creation(go_list_proposals):
        import dashlib
        import misc
        from sibcoind import SibcoinDaemon
>       sibcoind = SibcoinDaemon.from_sibcoin_conf(config.sibcoin_conf)
E       AttributeError: 'module' object has no attribute 'sibcoin_conf'

test/unit/models/test_superblocks.py:217: AttributeError
_______________________________________ test_deterministic_superblock_selection ________________________________________

go_list_superblocks = [{'AbsoluteYesCount': 1, 'AbstainCount': 0, 'CollateralHash': '0000000000000000000000000000000000000000000000000000000...1796d656e745f616d6f756e7473223a202232352e37353030303030307c32352e3735303030303030222c202274797065223a20327d5d5d', ...}]

    def test_deterministic_superblock_selection(go_list_superblocks):
        from sibcoind import SibcoinDaemon
>       sibcoind = SibcoinDaemon.from_sibcoin_conf(config.sibcoin_conf)
E       AttributeError: 'module' object has no attribute 'sibcoin_conf'

test/unit/models/test_superblocks.py:235: AttributeError
========================================= 8 failed, 15 passed in 0.47 seconds ==========================================
root@imagemasternode:~/sentinel#

**Comment by mceme** [comment]
dont use py.test

use this command $ :  ./venv/bin/python bin/sentinel.py

to run sentinel

**Comment by GJT67** [comment]
ImageCoind not synced with network! Awaiting full sync before running Sentinel.

How long does it take for ImageCoin to sync up. It has been running for 5 hours.

**Comment by mceme** [comment]
addnode=23.101.61.34:6998
addnode=51.77.144.203:6998
addnode=5.189.162.110:6998
addnode=94.16.122.165:6998
addnode=79.135.200.25:6998
addnode=54.38.158.185:6998
addnode=37.187.127.238:6998

**Comment by GJT67** [comment]
Do i put the add nodes i the ImageCoin.conf file on the VPS server ?

**Comment by GJT67** [comment]
The wallet simply will not sync. I dont understand, 

● ImageCoin.service - ImageCoin service
   Loaded: loaded (/etc/systemd/system/ImageCoin.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-12-19 09:46:49 UTC; 3h 8min ago
  Process: 1970 ExecStop=/usr/local/bin/ImageCoin-cli -conf=/root/.imagecoincore/imagecoin.conf -datadir=/root/.imagecoi
  Process: 1995 ExecStart=/usr/local/bin/ImageCoind -daemon -conf=/root/.imagecoincore/imagecoin.conf -datadir=/root/.im
 Main PID: 2002 (ImageCoind)
    Tasks: 16 (limit: 1108)
   CGroup: /system.slice/ImageCoin.service
           └─2002 /usr/local/bin/ImageCoind -daemon -conf=/root/.imagecoincore/imagecoin.conf -datadir=/root/.imagecoinc

Dec 19 09:46:49 imagemasternode systemd[1]: Starting ImageCoin service...
Dec 19 09:46:49 imagemasternode ImageCoind[1995]: ImageCoin Core server starting
Dec 19 09:46:49 imagemasternode systemd[1]: Started ImageCoin service.

root@imagemasternode:~/sentinel# ImageCoin-cli mnsync status
{
  "AssetID": 2,
  "AssetName": "MASTERNODE_SYNC_LIST",
  "AssetStartTime": 1576758064,
  "Attempt": 0,
  "IsBlockchainSynced": true,
  "IsMasternodeListSynced": false,
  "IsWinnersListSynced": false,
  "IsSynced": false,
  "IsFailed": false
}

**Comment by GJT67** [comment]
10 hours later and still the same

root@imagemasternode:~/sentinel# ./venv/bin/python bin/sentinel.py
ImageCoind not synced with network! Awaiting full sync before running Sentinel.

**Comment by GJT67** [comment]
The wallet does not sync, and i simply dont know why.

**Comment by mceme** [comment]
add nodes to imagecoin.conf
addnode=106.15.91.86:47116
addnode=108.61.165.183:47808
addnode=108.61.197.106:54074
addnode=121.40.147.152:36322
addnode=121.40.71.159:47922
addnode=123.132.232.10:6998
addnode=139.186.18.174:54029
addnode=144.202.54.124:56998
addnode=154.209.11.10:6998
addnode=154.209.11.14:6998
addnode=154.209.11.16:6998
addnode=154.209.11.27:6998
addnode=163.172.180.170:6998
addnode=173.208.175.146:51172
addnode=178.33.109.17:49650
addnode=185.162.248.212:6998
addnode=188.165.235.208:57323
addnode=209.250.226.92:43262
addnode=209.250.229.212:41966
addnode=222.186.175.58:6998
addnode=222.186.48.48:41108
addnode=222.186.48.48:47970
addnode=222.186.48.50:39062
addnode=222.186.48.50:50216
addnode=222.186.48.50:53362
addnode=39.100.87.246:39552
addnode=39.98.236.28:43688
addnode=39.99.32.113:49546
addnode=45.63.101.174:56384
addnode=45.63.69.3:44728
addnode=45.76.101.185:57132
addnode=45.76.139.104:55538
addnode=45.77.228.255:41398
addnode=45.77.90.245:39430
addnode=47.74.215.209:43222
addnode=47.74.222.152:52180
addnode=47.74.223.186:45396
addnode=47.74.223.95:55130
addnode=47.92.250.61:54202
addnode=47.92.37.172:60050
addnode=47.92.4.130:49320
addnode=47.92.87.183:40210
addnode=51.158.102.232:6998
addnode=54.37.204.173:38738
addnode=54.37.205.186:6998
addnode=54.38.158.185:6998
addnode=54.38.158.9:48084
addnode=79.135.200.25:6998
addnode=79.135.200.91:6998
addnode=92.60.47.244:52080
addnode=94.191.52.105:6998
addnode=95.179.207.238:60964
addnode=95.179.233.87:44876

**Comment by GJT67** [comment]
Is there a way to se if the sync is on

**Comment by GJT67** [comment]
root@imagemasternode:~/sentinel# ImageCoin-cli masternode status
{
  "outpoint": "0000000000000000000000000000000000000000000000000000000000000000-4294967295",
  "service": "95.179.252.131:6998",
  "status": "Not capable masternode: Masternode not in masternode list"

**Comment by GJT67** [comment]
root@imagemasternode:~/sentinel# ImageCoin-cli mnsync status
{
  "AssetID": 2,
  "AssetName": "MASTERNODE_SYNC_LIST",
  "AssetStartTime": 1576784499,
  "Attempt": 0,
  "IsBlockchainSynced": true,
  "IsMasternodeListSynced": false,
  "IsWinnersListSynced": false,
  "IsSynced": false,
  "IsFailed": false
}
root@imagemasternode:~/sentinel#

**Comment by GJT67** [comment]
root@imagemasternode:~/sentinel# ImageCoin-cli mnsync status
{
  "AssetID": -1,
  "AssetName": "MASTERNODE_SYNC_FAILED",
  "AssetStartTime": 1576784499,
  "Attempt": 0,
  "IsBlockchainSynced": false,
  "IsMasternodeListSynced": false,
  "IsWinnersListSynced": false,
  "IsSynced": false,
  "IsFailed": true

**Comment by GJT67** [comment]
root@imagemasternode:~/sentinel# ImageCoin-cli mnsync status
{
  "AssetID": 1,
  "AssetName": "MASTERNODE_SYNC_WAITING",
  "AssetStartTime": 1576785123,
  "Attempt": 0,
  "IsBlockchainSynced": false,
  "IsMasternodeListSynced": false,
  "IsWinnersListSynced": false,
  "IsSynced": false,
  "IsFailed": false

**Comment by GJT67** [comment]
sync ?

**Comment by mceme** [comment]
ImageCoin-cli getinfo

check blocks and connectins

**Comment by GJT67** [comment]
Last login: Thu Dec 19 21:05:19 2019 from 89.239.192.11
root@imagemasternode:~# ImageCoin-cli getinfo
{
  "version": 130102,
  "protocolversion": 70212,
  "walletversion": 61000,
  "balance": 0.00000000,
  "privatesend_balance": 0.00000000,
  "blocks": 0,
  "timeoffset": 0,
  "connections": 0,
  "proxy": "",
  "difficulty": 0.000244140625,
  "testnet": false,
  "keypoololdest": 1576774818,
  "keypoolsize": 999,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""

**Comment by mceme** [comment]
update your daemon current is 70218 Protocol
