### ISSUE TITLE
Not getting Imagecoin core to connect 

### ISSUE THREAD

**Issue by cedarfox** [mceme/ImageCoin#67]
Using windows 10 64 bit. Using Imagecoin core windows version IMG Core version v0.13.1.2-40d7e29-dirty (32-bit)
I have installed and allowed through zonealarm firewall. I am not using windows firewall but I still put it in allow anyway. I have also tried to disable zonealarm firewall but it didn't help.
I am getting other wallet core programs to work fine.  I am not running those at the same time. I am connecting from a home wifi network using comcast internet. Do I need to use port forwarding for this?
What ports is this thing using?   Any other ideas?
Thanks,
Mark

**Comment by cedarfox** [comment]
![img core](https://user-images.githubusercontent.com/39862483/74667504-640dc600-5171-11ea-8142-53a6913e9e4f.png)

**Comment by mceme** [comment]
add to imagecoin.conf:


addnode=23.101.61.34:6998
addnode=51.77.144.203:6998
addnode=5.189.162.110:6998
addnode=94.16.122.165:6998
addnode=79.135.200.25:6998
addnode=54.38.158.185:6998
addnode=37.187.127.238:6998

**Comment by harryweiyongjie** [comment]
hey, I get the same error, and I have add those node to conf file,but it still can't connet any node to sync.

> add to imagecoin.conf:
> 
> addnode=23.101.61.34:6998
> addnode=51.77.144.203:6998
> addnode=5.189.162.110:6998
> addnode=94.16.122.165:6998
> addnode=79.135.200.25:6998
> addnode=54.38.158.185:6998
> addnode=37.187.127.238:6998

**Comment by cedarfox** [comment]
It worked for me after mceme posted the node info and and put it in the file.

**Comment by mceme** [comment]
addnode=94.191.52.105:6998
addnode=15.164.152.188:6998
addnode=123.132.232.10:6998
addnode=118.24.254.234:6998
addnode=51.158.102.232:6998
addnode=163.172.180.170:6998
addnode=144.91.110.57:6998
addnode=79.135.200.86:6998


open port 6998
