### ISSUE TITLE
Version 1.0.33 not running on Ubunt 19.10

### ISSUE THREAD

**Issue by PanderMusubi** [mceme/ImageCoin#70]
Version 1.0.33 not running on Ubuntu 19.10, the error is

    imagecoin-qt: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory

The version of libboost needs to be higher or the particular libs should be included in the executable (statically linked.

**Comment by mceme** [comment]
need build wallet in our system

https://github.com/mceme/ImageCoin/blob/master/doc/build-unix.md
