### ISSUE TITLE
Install latest build

### ISSUE THREAD

**Issue by GJT67** [mceme/ImageCoin#78]
Fresh Unbuntu VPS, using the install procedure. Logged in as root

Gives this error.
● ImageCoin.service - ImageCoin service
   Loaded: loaded (/etc/systemd/system/ImageCoin.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-01-05 21:28:19 UTC; 6s ago
  Process: 12734 ExecStart=/usr/local/bin/ImageCoind -daemon -conf=/root/.imagecoincore/imagecoin.conf -datadir=/root/.imagecoincore (code=exited, status=127)

What is missing ?

**Comment by mceme** [comment]
try : sudo /usr/local/bin/ImageCoind

**Comment by GJT67** [comment]
Hello, gives this error

root@imagemasternode:~# sudo /usr/local/bin/ImageCoind
/usr/local/bin/ImageCoind: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory
root@imagemasternode:~#

**Comment by mceme** [comment]
sudo apt-get install libzmq3-dev


using ubuntu 20.04
